Timestamp: 11/04/22 11:12:33    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_3\model\service\modules\sales_module.py    -    ErrType: <class 'TypeError'>    -    ErrTraceback: <frame at 0x000001DEB7C43A60, file 'D:\\Strypes_Project\\strypes\\SWMS_3\\model\\service\\modules\\sales_module.py', line 304, code gen_inv_from_tr>    -    Generating invoice failed! You can generate invoices only for Sales!
