Timestamp: 28/03/22 08:36:02    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\users\user_mgmt.py    -    ErrType: <class 'json.decoder.JSONDecodeError'>    -    ErrTraceback: <frame at 0x000001AC8C9DFAF0, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\users\\user_mgmt.py', line 202, code load_users>    -    Error reading users file!
Timestamp: 28/03/22 08:36:02    -    ERROR    -    Logged from: D:\Strypes_Project\strypes\SWMS_2\Model\Modules\users\user_mgmt.py    -    ErrType: <class 'UnboundLocalError'>    -    ErrTraceback: <frame at 0x000001AC8C9DFAF0, file 'D:\\Strypes_Project\\strypes\\SWMS_2\\Model\\Modules\\users\\user_mgmt.py', line 219, code load_users>    -    Error Loading users!
